### ISSUE TITLE
Refactor to use VVM `compile_files`

### ISSUE THREAD

**Issue by fubuloubu** [ApeWorX/ape-vyper#37]
### Elevator pitch:
Use `vvm.compile_files` instead of `vvm.compile_source`

### Value:
Currently we use `compile_source` which places the files into a temporary path, which makes errors much harder to parse. This change will show the correct file that generated the error

### Dependencies:
Might be nicer to use alongside https://github.com/ApeWorX/ape/issues/660

### Design approach:
Just switch the methods

### Task list:
* [ ] Switch up the methods
* [ ] Do a ton of testing on different Vyper repos (Yearn-vaults, Curve DAO contracts)
* [ ] (optional) release update alongside core ape iterator refactor

### Estimated completion date:
1 week

### Design review:
Do not signoff unless:
- 1) agreed the tasks and design approach will achieve acceptance, and
- 2) the work can be completed by one person within the SLA.
Design reviewers should consider simpler approaches to achieve goals.

(Please leave a comment to sign off)

**Comment by fubuloubu** [comment]
Looks like Brownie actually uses `compile_standard` instead, which leverages `vyper-json` mode (and is more flexible e.g. we can sneak in interfaces easier)
